# Spam Email Classifier

## AI Internship Project

### Submitted By:
Aditi Jain

### Objective
The objective of this project is to build a machine learning model that can classify emails as Spam or Not Spam using Natural Language Processing and Machine Learning techniques.

In [1]:
# Import Required Libraries

import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

## Creating Dataset

For this project, a sample dataset containing spam and non-spam messages has been used.

In [3]:
data = {
    'label': [
        'spam','ham','spam','ham',
        'spam','ham','spam','ham',
        'spam','ham'
    ],

    'message': [
        'Win a free iPhone now',
        'Meeting at 3 PM tomorrow',
        'Congratulations you won 10000 rupees',
        'Please submit your assignment',
        'Claim your free reward',
        'Project discussion today',
        'Get cash instantly',
        'Class starts at 9 AM',
        'Exclusive offer just for you',
        'Please check the report'
    ]
}

df = pd.DataFrame(data)

df.head()

  label                               message
0  spam                 Win a free iPhone now
1   ham              Meeting at 3 PM tomorrow
2  spam  Congratulations you won 10000 rupees
3   ham         Please submit your assignment
4  spam                Claim your free reward

## Data Preprocessing

Converting text labels into numerical values.

In [4]:
df['label'] = df['label'].map({
    'ham':0,
    'spam':1
})

df.head()

   label                               message
0      1                 Win a free iPhone now
1      0              Meeting at 3 PM tomorrow
2      1  Congratulations you won 10000 rupees
3      0         Please submit your assignment
4      1                Claim your free reward

## Feature Extraction

Converting text into numerical form using TF-IDF Vectorization.

In [5]:
X = df['message']
Y = df['label']

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(X)

## Splitting Dataset

In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42
)

## Training Machine Learning Model

In [7]:
model = MultinomialNB()

model.fit(X_train, Y_train)

MultinomialNB()

## Model Accuracy

In [8]:
prediction = model.predict(X_test)

accuracy = accuracy_score(Y_test, prediction)

print("Accuracy:", accuracy)

Accuracy: 1.0

## Testing New Email Message

In [9]:
email = [
    "Congratulations! You have won ₹10,000"
]

email_features = vectorizer.transform(email)

result = model.predict(email_features)

if result[0] == 1:
    print("Spam Email")
else:
    print("Not Spam")

Spam Email

In [11]:
email = [
    "Please attend the project meeting tomorrow"
]

email_features = vectorizer.transform(email)

result = model.predict(email_features)

if result[0] == 1:
    print("Spam Email")
else:
    print("Not Spam")

Not Spam

# Conclusion

In this project, a Spam Email Classifier was developed using Machine Learning.

The Naive Bayes algorithm was used along with TF-IDF vectorization to classify email messages as spam or non-spam.

This project helped in understanding text preprocessing, feature extraction, model training, and prediction using Python.